import DayCard from './DayCard'
import jsPDF from 'jspdf'

export default function ItineraryDisplay({ itinerary, onReset }) {

    const downloadPDF = () => {
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
        const pageW = doc.internal.pageSize.getWidth()
        const pageH = doc.internal.pageSize.getHeight()
        const margin = 15
        const contentW = pageW - margin * 2
        let y = margin

        // Sanitize ALL text — removes ₹ (renders as ¹ in jsPDF) and all non-ASCII chars
        const clean = (str) => String(str || '').replace(/₹/g, 'Rs.').replace(/[^\x00-\x7F]/g, '')

        const checkNewPage = (neededHeight = 10) => {
            if (y + neededHeight > pageH - margin) {
                doc.addPage()
                y = margin
            }
        }

        // ── HEADER ──────────────────────────────────────────────────────────
        doc.setFillColor(102, 126, 234)
        doc.rect(0, 0, pageW, 35, 'F')
        doc.setFontSize(20)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(255, 255, 255)
        doc.text('AI Integrated Travel Itinerary Planner', pageW / 2, 14, { align: 'center' })
        doc.setFontSize(9)
        doc.setFont('helvetica', 'normal')
        doc.text('A Smart Personalized Travel Planning System Powered by Artificial Intelligence', pageW / 2, 22, { align: 'center' })
        y = 42

        // ── DESTINATION & META ───────────────────────────────────────────────
        doc.setFontSize(18)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(40, 40, 40)
        doc.text(clean(itinerary.destination), margin, y)
        y += 8
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(100, 100, 100)
        doc.text(
            clean(`Duration: ${itinerary.duration} Days   |   Total Trip Budget: Rs.${Number(itinerary.budget).toLocaleString()}   |   Generated by AI`),
            margin, y
        )
        y += 8

        // ── DIVIDER ──────────────────────────────────────────────────────────
        doc.setDrawColor(102, 126, 234)
        doc.setLineWidth(0.5)
        doc.line(margin, y, pageW - margin, y)
        y += 6

        // ── SUMMARY ──────────────────────────────────────────────────────────
        const summaryLines = doc.splitTextToSize(clean(itinerary.summary || ''), contentW)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(60, 60, 60)
        summaryLines.forEach(line => {
            checkNewPage(6)
            doc.text(line, margin, y)
            y += 5
        })
        y += 4

        // ── TIPS ─────────────────────────────────────────────────────────────
        if (itinerary.tips?.length) {
            checkNewPage(10)
            doc.setFontSize(11)
            doc.setFont('helvetica', 'bold')
            doc.setTextColor(102, 126, 234)
            doc.text('Pro Travel Tips', margin, y)
            y += 6
            itinerary.tips.forEach(tip => {
                const tipLines = doc.splitTextToSize(clean(`• ${tip}`), contentW)
                doc.setFontSize(9)
                doc.setFont('helvetica', 'normal')
                doc.setTextColor(80, 80, 80)
                tipLines.forEach(line => {
                    checkNewPage(6)
                    doc.text(line, margin, y)
                    y += 5
                })
            })
            y += 4
        }

        // ── TRANSPORT ────────────────────────────────────────────────────────
        if (itinerary.transport) {
            checkNewPage(30)
            doc.setFillColor(240, 240, 255)
            const transportTitleH = 10
            doc.roundedRect(margin, y, contentW, transportTitleH, 2, 2, 'F')
            doc.setFontSize(11)
            doc.setFont('helvetica', 'bold')
            doc.setTextColor(40, 40, 40)
            doc.text('Transport Guide', margin + 4, y + 7)
            y += transportTitleH + 4

            const toLines = doc.splitTextToSize(
                clean(`Getting There: ${itinerary.transport.toDestination}`),
                contentW - 8
            )
            doc.setFontSize(9)
            doc.setFont('helvetica', 'normal')
            doc.setTextColor(60, 60, 60)
            checkNewPage(toLines.length * 5 + 4)
            doc.text(toLines, margin + 4, y)
            y += toLines.length * 5 + 4

            const localLines = doc.splitTextToSize(
                clean(`Local Transport: ${itinerary.transport.local}`),
                contentW - 8
            )
            checkNewPage(localLines.length * 5 + 4)
            doc.text(localLines, margin + 4, y)
            y += localLines.length * 5 + 8
        }

        // ── DAYS ─────────────────────────────────────────────────────────────
        itinerary.days?.forEach(day => {
            checkNewPage(50)

            // Day header bar
            doc.setFillColor(102, 126, 234)
            doc.roundedRect(margin, y, contentW, 10, 3, 3, 'F')
            doc.setFontSize(11)
            doc.setFont('helvetica', 'bold')
            doc.setTextColor(255, 255, 255)
            doc.text(clean(`Day ${day.day}  —  ${day.theme}`), margin + 4, y + 7)
            doc.text(clean(`Est. ${day.estimatedDailyTotal}`), pageW - margin - 4, y + 7, { align: 'right' })
            y += 14

            const slots = ['morning', 'afternoon', 'evening']
            const labels = { morning: 'MORNING', afternoon: 'AFTERNOON', evening: 'EVENING' }

            // Activity slots
            slots.forEach(slot => {
                if (!day[slot]) return
                const descLines = doc.splitTextToSize(clean(day[slot].description || ''), contentW - 60)
                const slotH = Math.max(22, descLines.length * 5 + 18)
                checkNewPage(slotH + 4)
                doc.setFillColor(248, 248, 255)
                doc.roundedRect(margin, y, contentW, slotH, 2, 2, 'F')
                doc.setFontSize(9)
                doc.setFont('helvetica', 'bold')
                doc.setTextColor(102, 126, 234)
                doc.text(labels[slot], margin + 3, y + 6)
                doc.setFont('helvetica', 'bold')
                doc.setTextColor(30, 30, 30)
                doc.text(clean(day[slot].activity || ''), margin + 3, y + 12)
                doc.setFont('helvetica', 'normal')
                doc.setTextColor(80, 80, 80)
                doc.text(descLines, margin + 3, y + 17)
                doc.setTextColor(46, 125, 50)
                doc.setFont('helvetica', 'bold')
                doc.text(
                    clean(`${day[slot].cost}  |  ${day[slot].duration}`),
                    pageW - margin - 4, y + 12, { align: 'right' }
                )
                y += slotH + 3
            })

            // Food recommendations
            if (day.food) {
                const bLines = doc.splitTextToSize(clean(`Breakfast: ${day.food.breakfast}`), contentW / 3 - 6)
                const lLines = doc.splitTextToSize(clean(`Lunch: ${day.food.lunch}`), contentW / 3 - 6)
                const dLines = doc.splitTextToSize(clean(`Dinner: ${day.food.dinner}`), contentW / 3 - 6)
                const maxFoodLines = Math.max(bLines.length, lLines.length, dLines.length)
                const foodBoxH = maxFoodLines * 5 + 14
                checkNewPage(foodBoxH + 4)
                doc.setFillColor(255, 249, 240)
                doc.roundedRect(margin, y, contentW, foodBoxH, 2, 2, 'F')
                doc.setFontSize(9)
                doc.setFont('helvetica', 'bold')
                doc.setTextColor(230, 126, 34)
                doc.text('Food Recommendations', margin + 3, y + 6)
                doc.setFont('helvetica', 'normal')
                doc.setTextColor(60, 60, 60)
                doc.text(bLines, margin + 3, y + 13)
                doc.text(lLines, margin + contentW / 3 + 3, y + 13)
                doc.text(dLines, margin + (contentW / 3) * 2 + 3, y + 13)
                y += foodBoxH + 4
            }

            // Where to Stay — HIDDEN on last/departure day
            if (day.accommodation && day.day !== itinerary.duration) {
                const stayText = clean(
                    `${day.accommodation.name}  —  ${day.accommodation.type}  —  ${day.accommodation.estimatedCost}`
                )
                const stayLines = doc.splitTextToSize(stayText, contentW - 8)
                const stayBoxH = stayLines.length * 5 + 14
                checkNewPage(stayBoxH + 4)
                doc.setFillColor(245, 240, 255)
                doc.roundedRect(margin, y, contentW, stayBoxH, 2, 2, 'F')
                doc.setFontSize(9)
                doc.setFont('helvetica', 'bold')
                doc.setTextColor(142, 68, 173)
                doc.text('Where to Stay', margin + 3, y + 6)
                doc.setFont('helvetica', 'normal')
                doc.setTextColor(60, 60, 60)
                doc.text(stayLines, margin + 3, y + 11)
                y += stayBoxH + 4
            }

            y += 6
        })

        // ── CLOSING SECTION ──────────────────────────────────────────────────
        if (itinerary.closing) {
            checkNewPage(20)
            doc.setDrawColor(102, 126, 234)
            doc.setLineWidth(0.5)
            doc.line(margin, y, pageW - margin, y)
            y += 8

            // Packing list — numbered, 2 per row, compact
            if (itinerary.closing.thingsToPack?.length) {
                checkNewPage(12)
                doc.setFontSize(12)
                doc.setFont('helvetica', 'bold')
                doc.setTextColor(102, 126, 234)
                doc.text('Things to Pack & Carry', margin, y)
                y += 6

                doc.setFontSize(9)
                doc.setFont('helvetica', 'normal')
                doc.setTextColor(60, 60, 60)
                const colW = contentW / 2
                const items = itinerary.closing.thingsToPack
                for (let i = 0; i < items.length; i += 2) {
                    checkNewPage(6)
                    const left = clean(`${i + 1}. ${items[i].charAt(0).toUpperCase() + items[i].slice(1).toLowerCase()}`)
                    doc.text(left, margin + 2, y)
                    if (items[i + 1]) {
                        const right = clean(`${i + 2}. ${items[i + 1].charAt(0).toUpperCase() + items[i + 1].slice(1).toLowerCase()}`)
                        doc.text(right, margin + colW + 2, y)
                    }
                    y += 5.5
                }
                y += 4
            }

            // Wish message — fully wrapped, no truncation
            if (itinerary.closing.wishMessage) {
                const wishLines = doc.splitTextToSize(
                    clean(itinerary.closing.wishMessage),
                    contentW - 10
                )
                const boxH = wishLines.length * 6 + 12
                checkNewPage(boxH + 4)
                doc.setFillColor(240, 248, 255)
                doc.roundedRect(margin, y, contentW, boxH, 3, 3, 'F')
                doc.setFontSize(10)
                doc.setFont('helvetica', 'bolditalic')
                doc.setTextColor(70, 100, 180)
                doc.text(wishLines, margin + 5, y + 8)
                y += boxH + 8
            }
        }

        // ── FOOTER ───────────────────────────────────────────────────────────
        doc.setFontSize(8)
        doc.setTextColor(150, 150, 150)
        doc.setFont('helvetica', 'italic')
        doc.text('Generated by AI Integrated Travel Itinerary Planner', pageW / 2, pageH - 8, { align: 'center' })

        doc.save(`${clean(itinerary.destination)}-itinerary.pdf`)
    }

    return (
        <div className="itinerary-container" id="itinerary-content">
            <div className="itinerary-header">
                <h2>📍 {itinerary.destination}</h2>
                <div className="itinerary-meta">
                    <span className="meta-badge">📅 {itinerary.duration} Days</span>
                    <span className="meta-badge">💰 Total Budget: ₹{Number(itinerary.budget).toLocaleString()}</span>
                </div>
                <p className="summary-text">{itinerary.summary}</p>

                {itinerary.tips && (
                    <div className="tips-section">
                        <h4>Pro Travel Tips</h4>
                        <ul>
                            {itinerary.tips.map((tip, i) => <li key={i}>{tip}</li>)}
                        </ul>
                    </div>
                )}

                <div className="action-buttons">
                    <button className="btn-pdf" onClick={downloadPDF}>📄 Download PDF</button>
                    <button className="btn-new" onClick={onReset}>✈️ Plan Another Trip</button>
                </div>
            </div>

            {itinerary.transport && (
                <div className="transport-card">
                    <h3>🚗 How to Get There & Move Around</h3>
                    <div className="transport-item">
                        <strong>Getting There:</strong> {itinerary.transport.toDestination}
                    </div>
                    <div className="transport-item">
                        <strong>Local Transport:</strong> {itinerary.transport.local}
                    </div>
                    <div style={{ marginTop: '14px' }}>
                        <p style={{ fontWeight: 600, color: '#4a4a6a', marginBottom: '10px' }}>
                            🎟️ Book Your Travel to {itinerary.transport.destinationCity}
                        </p>
                        <div className="booking-buttons">
                            <button className="book-btn flight" onClick={() => {
                                const from = encodeURIComponent(itinerary.transport.originCity || '')
                                const to = encodeURIComponent(itinerary.transport.destinationCity || '')
                                window.open(`https://www.google.com/travel/flights?q=flights+from+${from}+to+${to}`, '_blank')
                            }}>✈️ Google Flights</button>
                            <button className="book-btn train" onClick={() => {
                                window.open('https://www.irctc.co.in/nget/train-search', '_blank')
                            }}>🚆 IRCTC Train</button>
                            <button className="book-btn bus" onClick={() => {
                                const to = encodeURIComponent(itinerary.transport.destinationCity || '')
                                window.open(`https://www.redbus.in/bus-tickets/bus-to-${to.toLowerCase()}`, '_blank')
                            }}>🚌 redBus</button>
                        </div>
                    </div>
                </div>
            )}

            {itinerary.days && itinerary.days.map(day => (
                <DayCard key={day.day} day={day} totalDays={itinerary.duration} />
            ))}

            {itinerary.closing && (
                <div className="transport-card" style={{ marginTop: '16px' }}>
                    {itinerary.closing.thingsToPack?.length > 0 && (
                        <>
                            <h3>🎒 Things to Pack & Carry</h3>
                            <div style={{
                                display: 'grid',
                                gridTemplateColumns: '1fr 1fr',
                                gap: '5px',
                                margin: '10px 0'
                            }}>
                                {itinerary.closing.thingsToPack.map((item, i) => (
                                    <div key={i} style={{
                                        color: '#444',
                                        fontSize: '0.88rem',
                                        padding: '5px 10px',
                                        background: '#f4f4ff',
                                        borderRadius: '7px',
                                        borderLeft: '3px solid #667eea',
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: '6px'
                                    }}>
                                        <span style={{ color: '#667eea', fontWeight: 700, minWidth: '18px' }}>{i + 1}.</span>
                                        {item.charAt(0).toUpperCase() + item.slice(1).toLowerCase()}
                                    </div>
                                ))}
                            </div>
                        </>
                    )}
                    {itinerary.closing.wishMessage && (
                        <div style={{
                            background: 'linear-gradient(135deg, #f0f4ff, #e8f0fe)',
                            borderRadius: '12px',
                            padding: '16px 20px',
                            marginTop: '14px',
                            borderLeft: '4px solid #667eea'
                        }}>
                            <p style={{ color: '#4a4a8a', fontStyle: 'italic', lineHeight: '1.7', margin: 0 }}>
                                🌟 {itinerary.closing.wishMessage}
                            </p>
                        </div>
                    )}
                </div>
            )}
        </div>
    )
}